version: '3'
services:

  go-server:
    image: gocd/gocd-server:v17.8.0
    networks:
      - gocd
    deploy:
      mode: global
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./data:/godata
      - ./go:/home/go
    restart: always

  go-agent:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gocd
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      GO_SERVER_URL: "https://go-server:8154/go"
    volumes:
      - ./data/pipelines:/godata/pipelines
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - go-server:go-server
    depends_on:
      - go-server
    restart: always

networks:
  gocd:
