pipelines:
  yufei-app:
    group: damnops
    materials:
      damnopsgit:
        git: https://github.com/damnops/homework.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: docker build -t yufei-app yufei/project
