pipelines:
  yufei-app:
    group: damnops
    materials:
      damnopsgit:
        git: https://github.com/damnops/homework.git
    stages:
      - test:
          jobs:
            unit-test:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "unit test passed!"

      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                    - "yufei/auto/build"

      - archive:
          jobs:
            push-to-registry:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                    - "yufei/auto/deploy"

      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: echo
                    arguments:
                    - "deploy succeed!"
