pipelines:
  yufei-app:
    group: damnops
    materials:
      damnopsgit:
        git: https://github.com/damnops/homework.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec: docker build -t yufei-app:$BUILD_NUMBER yufei/project
i
