#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/functions

declare -a RUNLIST=("app" "mongodb" "migration")

for r in ${RUNLIST[@]}; do
	docker-compose --project-name ${PROJECTNAME} start ${r}
done