wangyue/homework3/docker-demo/development/app/DockerfileFROM mongo:latest
MAINTAINER "Wang Yue" <wywy08271@outlook.com>

WORKDIR /usr/src/app
COPY . .

ENTRYPOINT ["/usr/src/app/entrypoint"]
CMD ["/usr/src/app/run"]