#!/bin/bash

echo "Trying to connect to ${DB_HOST} ..."
while ! mongo ${DB_HOST}:${DB_PORT}/${DB_NAME} 1>/dev/null
do
  echo "Failed to connect to ${DB_HOST}, trying again in 3 seconds..."
  sleep 3
done
echo "Database connection successful. Continuing..."

exec $@