#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/functions

docker-compose --project-name ${PROJECTNAME} -f gitlab.yaml down --volumes
docker-compose --project-name ${PROJECTNAME} -f jenkins.yaml down --volumes
docker-compose --project-name ${PROJECTNAME} -f registry.yaml down --volumes