#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/functions

docker-compose --project-name ${PROJECTNAME} -f gitlab.yaml stop
docker-compose --project-name ${PROJECTNAME} -f jenkins.yaml stop
docker-compose --project-name ${PROJECTNAME} -f registry.yaml stop