#! /bin/bash -e

cd $(dirname $0)/..
source ./auto/functions

docker-compose --project-name ${PROJECTNAME} -f gitlab.yaml up -d
docker-compose --project-name ${PROJECTNAME} -f jenkins.yaml up -d
docker-compose --project-name ${PROJECTNAME} -f registry.yaml up -d